### ISSUE TITLE
Add plugins

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/critical-site-health#2]
```yaml
# These plugins must be active
plugin_active:
# These plugins must not be active
plugin_inactive:
```
